name: Monitor UNICA

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script
        env:
          EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
          EMAIL_SENHA: ${{ secrets.EMAIL_SENHA }}
          EMAIL_DESTINOS: ${{ secrets.EMAIL_DESTINOS }}
        run: python main.py
